angular
    .module('myApp')
    .service('CustomersService',CustomersService);

CustomersService.$inject = ["$http"];

// Service
function CustomersService ($http) {
    var self = this;
    // Bindable members
    self.customers;
    self.customersCodes;
    // Public Methods
    self.getAll = getAll;
    self.getCodes = getCodes;
    self.post = post;
    self.remove = remove;
    self.checkEmailAvailability = checkEmailAvailability;
    
    function getAll () {
        return $http
                .get('https://angularbeds.firebaseio.com/aleix/customers.json')
                .then(function (response) {                
                    self.customers = response.data;
                    return self.customers;
                });
    };

    function getCodes () {
        return $http
                .get('https://angularbeds.firebaseio.com/aleix/customersCodes.json')
                .then(function (response) {
                    // Update model
                    self.customersCodes = response.data;
                    return self.customersCodes;
                });
    };
    
    // Add a customer
    function post (data) {
        return $http
                .post('https://angularbeds.firebaseio.com/aleix/customers.json', data)
                .then(function(response){
                    // Update Model adding the new customer with the id generated by the server
                    return self.customers[response.data.name] = data;
                });
    };

    // Remove a customer
    function remove (id) {
        return $http
                .delete('https://angularbeds.firebaseio.com/aleix/customers/'+ id + '.json')
                .then(function(response){
                    // Update model
                    delete self.customers[id];
                    return self.customers;
                });
    };

    // Check if the email is not already registered
    function checkEmailAvailability (email, customers) {
        if (!customers) { var customers = self.customers };
        var taken = false;
        angular.forEach(customers, function(customer){
             if (email === customer.email) {
                taken = true;
             }
        });
        return taken;
    }
    
}